export const GET_NEW_DECK_REQUEST = 'GET_NEW_DECK_REQUEST';
export const GET_NEW_DECK_SUCCESS = 'GET_NEW_DECK_SUCCESS';

export const SHUFFLE_DECK_REQUEST = 'SHUFFLE_DECK_REQUEST';
export const SHUFFLE_DECK_SUCCESS = 'SHUFFLE_DECK_SUCCESS';

export const DRAW_DECK_REQUEST = 'DRAW_DECK_REQUEST';
export const DRAW_DECK_SUCCESS = 'DRAW_DECK_SUCCESS';

export const GAME_NEXT_ROUND = 'GAME_NEXT_ROUND';
export const GAME_RESET_ROUND = 'GAME_RESET_ROUND';

export const GAME_SET_SCORE = 'GAME_SET_SCORE';

export const REQUEST_FAIL = 'REQUEST_FAIL';