export const GET_NEW_DECK_REQUEST = 'GET_NEW_DECK_REQUEST';
export const GET_NEW_DECK_SUCCESS = 'GET_NEW_DECK_SUCCESS';

export const SHUFFLE_DECK_REQUEST = 'SHUFFLE_DECK_REQUEST';
export const SHUFFLE_DECK_SUCCESS = 'SHUFFLE_DECK_SUCCESS';

export const DRAW_DECK_REQUEST = 'DRAW_DECK_REQUEST';
export const DRAW_DECK_SUCCESS = 'DRAW_DECK_SUCCESS';

export const REQUEST_FAIL = 'REQUEST_FAIL';